services:
  # api:
  #   container_name: email-services
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   ports:
  #     - 4652:8080
  #   depends_on: ["pg"]
  #   networks:
  #     email-services-networks:

  database:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=docker
      - POSTGRES_DB=email-services
# networks:
#   email-services-networks:
#     driver: bridge
