services:
  api:
    container_name: email-services
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 4652:8080
    depends_on: ["pg"]
    networks:
      email-services-networks:

  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=email-services
    networks:
      email-services-networks:
        aliases:
          - "sql"

networks:
  email-services-networks:
    driver: bridge
